version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: duties
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - '5732:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/duties
      - LOG_LEVEL=info
    command: npm start
    depends_on:
      - db
